application: tasksprime
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /oauth2callback
  script: oauth2client/appengine.py
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: .*
  script: main.py
