application: tasksprime
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: .*
  static_dir: client/
- url: /js
  static_dir: client/js
- url: /css
  static_dir: client/css

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^js/node_modules
- ^client/js/node_modules
